name: e2e_test
on:
  workflow_dispatch:
   inputs:
      guard:
        description: guard url    
        required: true
      branch:
        description: branch name
        required: true
      expected:
        description: expected results
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Clean up Auto Remediation PRs
      uses: actions/stale@v4
      with:
        days-before-stale: 0.5
        days-before-close: 0.5
        delete-branch: true
        
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
  
    - name: Run Magalix Action 
      if: ${{ github.event.inputs.branch == 'main' }}
      uses: magalixcorp/magalix-action@main
      with:
        webhook: ${{ github.event.inputs.guard }}
        branch: ${{ github.event.inputs.branch }}
        no-exit-error: true
        export-to: result.json

    - name: Run Magalix Action 
      if: ${{ github.event.inputs.branch == 'dev' }}
      uses: magalixcorp/magalix-action@dev
      with:
        webhook: ${{ github.event.inputs.guard }}
        branch: ${{ github.event.inputs.branch }}
        no-exit-error: true
        export-to: result.json

    - name: 'Upload Result'
      uses: actions/upload-artifact@v2
      with:
        name: result.json
        path: result.json
        retention-days: 7

    - name: Validate Results
      run: python3 e2e.py '${{ github.event.inputs.expected }}'
  
