name: Magalix

on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * *

jobs:
  run:
    strategy:
      matrix:
        branch:
        - dev
        - main
    
    runs-on: ubuntu-latest
    steps:

    - name: Clean up Auto Remediation PRs
      uses: actions/stale@v4
      with:
        days-before-stale: 0.5
        days-before-close: 0.5
        delete-branch: true
        
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
  
    - name: Run Magalix Action 
      if: ${{ matrix.branch == 'main' }}
      uses: magalixcorp/magalix-action@main
      with:
        webhook: ${{ secrets.PROD_GUARD }}
        branch: ${{ matrix.branch }}
        export-to: result.json

    - name: Run Magalix Action 
      if: ${{ matrix.branch == 'dev' }}
      uses: magalixcorp/magalix-action@dev
      with:
        webhook: 'https://console.aws.dev.magalix.com/api/v1/kubeguard/866df433-d02d-433c-82eb-8f47475506be/75b1cde0-c730-4da8-a2ed-bbe65eaa429b'
        branch: ${{ matrix.branch }}
        export-to: result.json

    - name: 'Upload Result'
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: result-${{ matrix.branch }}.json
        path: result.json
        retention-days: 7
    
    - name: Validate Results
      if: ${{ always() }}
      run: python3 tests.py 
      env:
        ENVIRONMENT_BRANCH: ${{ matrix.branch }}
        SLACK_DEV_CHANNEL: ${{ secrets.SLACK_DEV_CHANNEL }}
        SLACK_PRD_CHANNEL: ${{ secrets.SLACK_PRD_CHANNEL }}
